efi="/dev/sda1"
root="/dev/sda2"
home="/dev/sda3"
swap="/dev/sda4"
swapfile=False
cpu="intel"
bootloader="systemd-boot" # 1 for systemd-boot, 2 for grub
hostname='jarvis'
username='partha'
video_drivers="xf86-video-intel xf86-video-ati" #nvidia
